-- MySQL Script generated by MySQL Workbench
-- Fri Jul 15 11:08:41 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Designer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Designer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Designer` DEFAULT CHARACTER SET utf8 ;
USE `Designer` ;

-- -----------------------------------------------------
-- Table `Designer`.`designers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`designers` ;

CREATE TABLE IF NOT EXISTS `Designer`.`designers` (
  `designer_id` INT NOT NULL,
  `first_name` TEXT NOT NULL,
  `last_name` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  PRIMARY KEY (`designer_id`));


-- -----------------------------------------------------
-- Table `Designer`.`canvases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`canvases` ;

CREATE TABLE IF NOT EXISTS `Designer`.`canvases` (
  `canvas_id` INT UNSIGNED NOT NULL,
  `image_path` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`canvas_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Designer`.`designs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`designs` ;

CREATE TABLE IF NOT EXISTS `Designer`.`designs` (
  `design_id` INT UNSIGNED NOT NULL,
  `designer_id` INT UNSIGNED NOT NULL,
  `checked` TINYINT(1) NOT NULL,
  `emailed` TINYINT(1) NULL,
  `paid` TINYINT(1) NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `image_path` VARCHAR(45) NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `canvas_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`design_id`),
  INDEX `designs_fk0` (`designer_id` ASC),
  UNIQUE INDEX `image_path_UNIQUE` (`image_path` ASC),
  UNIQUE INDEX `product_name_UNIQUE` (`product_name` ASC),
  INDEX `canvas_id_idx` (`canvas_id` ASC),
  CONSTRAINT `designs_fk0`
    FOREIGN KEY (`designer_id`)
    REFERENCES `Designer`.`designers` (`designer_id`),
  CONSTRAINT `canvas_id`
    FOREIGN KEY (`canvas_id`)
    REFERENCES `Designer`.`canvases` (`canvas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Designer`.`text_entries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`text_entries` ;

CREATE TABLE IF NOT EXISTS `Designer`.`text_entries` (
  `text_id` INT NOT NULL,
  `text_entry` TEXT NOT NULL,
  `font` TEXT NOT NULL,
  `colour` TEXT NOT NULL,
  `location` TEXT NOT NULL,
  `design_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`text_id`),
  INDEX `design_id_idx` (`design_id` ASC),
  CONSTRAINT `design_id`
    FOREIGN KEY (`design_id`)
    REFERENCES `Designer`.`designs` (`designer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `Designer`.`design_uploads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`design_uploads` ;

CREATE TABLE IF NOT EXISTS `Designer`.`design_uploads` (
  `design_upload_id` INT NOT NULL,
  `file_path` VARCHAR(45) NOT NULL,
  `design_id` INT UNSIGNED NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`design_upload_id`),
  UNIQUE INDEX `file_path_UNIQUE` (`file_path` ASC),
  INDEX `design_id_idx` (`design_id` ASC),
  CONSTRAINT `design_id`
    FOREIGN KEY (`design_id`)
    REFERENCES `Designer`.`designs` (`designer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Designer`.`productCatagories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`productCatagories` ;

CREATE TABLE IF NOT EXISTS `Designer`.`productCatagories` (
  `productCatagory_id` INT NOT NULL,
  `catagory_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`productCatagory_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Designer`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`products` ;

CREATE TABLE IF NOT EXISTS `Designer`.`products` (
  `product_id` INT UNSIGNED NOT NULL,
  `product_name` VARCHAR(45) NOT NULL,
  `price` FLOAT UNSIGNED NOT NULL,
  `product_weight` FLOAT UNSIGNED NOT NULL,
  `update_date` VARCHAR(45) NULL DEFAULT 'CURRENT_TIMESTAMP',
  `stock` INT UNSIGNED NULL,
  `number_of_orders` INT UNSIGNED NOT NULL,
  `productCatagory_id` INT NULL,
  `design_id` INT UNSIGNED NOT NULL,
  `productscol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_name_UNIQUE` (`product_name` ASC),
  UNIQUE INDEX `product_weight_UNIQUE` (`product_weight` ASC),
  INDEX `productCatagory_id_idx` (`productCatagory_id` ASC),
  UNIQUE INDEX `design_id_UNIQUE` (`design_id` ASC),
  UNIQUE INDEX `productscol_UNIQUE` (`productscol` ASC),
  CONSTRAINT `productCatagory_id`
    FOREIGN KEY (`productCatagory_id`)
    REFERENCES `Designer`.`productCatagories` (`productCatagory_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `design_id`
    FOREIGN KEY (`design_id`)
    REFERENCES `Designer`.`designs` (`design_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Designer`.`host_designs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`host_designs` ;

CREATE TABLE IF NOT EXISTS `Designer`.`host_designs` (
  `host_designs_id` INT NOT NULL,
  `file_path` VARCHAR(45) NOT NULL,
  `size` VARCHAR(45) NOT NULL,
  `design_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`host_designs_id`),
  INDEX `design_id_idx` (`design_id` ASC),
  CONSTRAINT `design_id`
    FOREIGN KEY (`design_id`)
    REFERENCES `Designer`.`designs` (`design_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Designer`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`users` ;

CREATE TABLE IF NOT EXISTS `Designer`.`users` (
  `user_id` INT UNSIGNED NOT NULL,
  `username` (16) NOT NULL,
  `email` (255) NULL,
  `password` (32) NOT NULL,
  `created_at` VARCHAR(45) NULL DEFAULT 'CURRENT_TIMESTAMP',
  `number_of_orders` INT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `shipping_city` VARCHAR(45) NULL,
  `shipping_address` VARCHAR(45) NULL,
  `shipping_address_two` VARCHAR(45) NULL,
  `shipping_province` VARCHAR(45) NULL,
  `shipping_postalcode` VARCHAR(45) NULL,
  `shipping_country` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC));


-- -----------------------------------------------------
-- Table `Designer`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`orders` ;

CREATE TABLE IF NOT EXISTS `Designer`.`orders` (
  `order_id` INT UNSIGNED NOT NULL,
  `total_price` FLOAT UNSIGNED NOT NULL,
  `user_order` TINYINT(1) NOT NULL,
  `user_id` INT UNSIGNED NULL,
  `shipping_first_name` VARCHAR(45) NOT NULL,
  `shipping_address` VARCHAR(45) NOT NULL,
  `shipping_address_two` VARCHAR(45) NULL,
  `shipping_city` VARCHAR(45) NOT NULL,
  `shipping_province` VARCHAR(45) NOT NULL,
  `shipping_postalcode` VARCHAR(45) NOT NULL,
  `shipping_country` VARCHAR(45) NOT NULL,
  `shipping_phone` VARCHAR(45) NOT NULL,
  `shipping_price` FLOAT UNSIGNED NOT NULL,
  `order_email` VARCHAR(45) NOT NULL,
  `order_date` VARCHAR(45) NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  `order_shipped` TINYINT(1) NOT NULL,
  `tracking_number` VARCHAR(45) NULL,
  `shipping_last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_id`, `user_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `Designer`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Designer`.`order_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`order_product` ;

CREATE TABLE IF NOT EXISTS `Designer`.`order_product` (
  `order_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC),
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `Designer`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `Designer`.`products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Designer`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`comments` ;

CREATE TABLE IF NOT EXISTS `Designer`.`comments` (
  `comment_id` INT UNSIGNED NOT NULL,
  `comment` VARCHAR(45) NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`comment_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC),
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `Designer`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Designer`.`ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`ratings` ;

CREATE TABLE IF NOT EXISTS `Designer`.`ratings` (
  `rating_id` INT UNSIGNED NOT NULL,
  `rating` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`rating_id`),
  UNIQUE INDEX `rating_id_UNIQUE` (`rating_id` ASC),
  INDEX `product_id_idx` (`product_id` ASC),
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `Designer`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Designer`.`carts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`carts` ;

CREATE TABLE IF NOT EXISTS `Designer`.`carts` (
  `cart_id` INT UNSIGNED NOT NULL,
  `session_id` VARCHAR(45) NOT NULL DEFAULT '0',
  `ip_address` VARCHAR(45) NOT NULL DEFAULT '0',
  `last_activity` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`cart_id`),
  UNIQUE INDEX `cart_id_UNIQUE` (`cart_id` ASC),
  UNIQUE INDEX `session_id_UNIQUE` (`session_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Designer`.`cart_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Designer`.`cart_product` ;

CREATE TABLE IF NOT EXISTS `Designer`.`cart_product` (
  `cart_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  INDEX `cart_id_idx` (`cart_id` ASC),
  INDEX `product_id_idx` (`product_id` ASC),
  CONSTRAINT `cart_id`
    FOREIGN KEY (`cart_id`)
    REFERENCES `Designer`.`carts` (`cart_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `Designer`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
